# Generated by Django 6.0.4 on 2026-05-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.propriedade'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.subcategoria'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipo'),
        ),
    ]
